=== ces3-2023-1/Entregable1/src/resourses/Producto.dtd
<!ELEMENT productos (producto*)>
<!ELEMENT producto (idCategoria+,codigoProd+,nombreProd+,descripcionProd+)>
<!ATTLIST producto idProducto #IMPLIED>
<!ELEMENT idCategoria (#PCDATA)>
<!ELEMENT codigoProd (#PCDATA)>
<!ELEMENT nombreProd (#PCDATA)>
<!ELEMENT descripcionProd (#PCDATA)>

=== ces3-2023-1/Entregable1/src/resourses/Producto.xml
<?xml version="1.0" encoding="UTF-8" standalone ="yes" ?>

<!DOCTYPE productos SYSTEM "Producto.dtd">

<productos>
    <!-- Este es un comentario
    -->
    <producto idProducto ="01" >
        <idCategoria>03</idCategoria>
        <codigoProd>SCFD8658</codigoProd>
        <nombreProd>Computador de escritorio</nombreProd>
        <descripcionProd>Marca HP, procesador Intel i7</descripcionProd>
    </producto>

    <producto idProducto ="01" >
        <idCategoria>03</idCategoria>
        <codigoProd>SCFD8658</codigoProd>
        <nombreProd>Computador de escritorio</nombreProd>
        <descripcionProd>Marca HP, procesador Intel i7</descripcionProd>
    </producto>

</productos>
